### PR TITLE
Hold trait notification when setting multiple attributes from js

### PR DESCRIPTION
**Pull request by SylvainCorlay**
This is holding notifications when setting multiple trait attributes from the front-end

Currently, when doing something like the following in a widget view:

```JavaScript
this.model.set('x', x);
this.model.set('y', y);
this.touch();
```
trait assignments and notifications are made and sent in the (arbitrary) order in which the attributes are set from the bulk updates in the backend. If the first set is `'x'` and the change handler for `x` uses `'y'`, it would use the old value...

This should solve this issue using the new `hold_trait_notifications` context manager.

### CODE REVIEW

**Comment by jdfreder** [comment]
Does the same apply back-end to front-end?  i.e. if I use hold sync, set a couple traits in python, do the Javascript backbone model change events fire once all of the values are set, or just when one is set.  I'm not sure these behaviors should be inconsistent.

**Comment by SylvainCorlay** [comment]
Wow, instead of replying, I started editing your comment (involuntarily). I think that it is once everything is set.

**Comment by jasongrout** [comment]
This makes a lot of sense to do, as far as I'm concerned.

**Comment by jasongrout** [comment]
@ssunkara1 found a subtle issue with this and the property lock in set_state.  Sylvain is looking into it.

**Comment by SylvainCorlay** [comment]
@jasongrout I addressed your comments.

**Comment by SylvainCorlay** [comment]
Hum Python 3 tests failing.

**Comment by jasongrout** [comment]
This looks good to me.  I'll test it and merge it if it still looks okay.

**Comment by jasongrout** [comment]
Actually, @SylvainCorlay, could you write a short test for this?  Maybe a sync message that sets two values equal, with a validation check that the two values are always equal?

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
